### PR TITLE
Add backwards compatible python3 support

### PR DESCRIPTION
**Pull request by Dylgar**
Theses changes get the project running with python2 and python3(#143).  Unfortunately I am unable to run the tests from a clean checkout/environment with python2 without any failures so cannot confirm that it works perfectly. That being said, none of the tests have started failing due to the changes.

### CODE REVIEW

**Comment by matclayton** [comment]
Thanks for this, its hugely welcome! I'll look at getting it merged as soon as I get some time to vet it all properly.

**Comment by tysonclugg** [comment]
@matclayton I've updated `tox.ini` in PR #159, with that version you may uncomment the relevant lines to enable Python 3 tests.  Any chance of reviewing this and #159 and making a release later this week?

**Comment by matclayton** [comment]
Sorry I'd got swept away with work :) We still use this module very actively, infact I'm working on it today. So I'll try and find time to look at this, probably Friday. We're very happy to land Python3 support, but we'll require 2.7 as well for now. We're still a python2.7 (Django 1.11) shop, so I feel much more comfortable releasing code we still have in production and under heavy use! We'll be pushing to 3.x asap though!

**Comment by matclayton** [comment]
Closing this, as the changes we're applied as part of #161 + extended to add tox coverage for Python 3

**Pull request closed without merging**
