### PR TITLE
Python 3 (with tests)

### PR DESCRIPTION
**Pull request by tysonclugg**
@matclayton 

* Drops support for Django 1.7 (not supported, conflicts with jsonfield 2.0).
* Add support Python 3.3, 3.4, 3.5 and 3.6.
* Also adds config for Travis CI.
* Second class support for PyPy (tox tests pass) since Travis CI PyPy install is broken.
* All tests passing. :slightly_smiling_face: 

Test results from Travis CI at https://travis-ci.org/tysonclugg/django-experiments:
selection_269

Test results from tox on my machine:
selection_270

### CODE REVIEW

**Comment by matclayton** [comment]
Thanks not looked at this in depth, more than happy to drop 1.7! We currently use codeship for CI, so I'd like to get it working on there as well. I'll need to take some time and figure it out, but once thats done, I'm happy to merge/ship this out.

**Comment by tysonclugg** [comment]
I tried to look at your Codeship builds, but they're not public?  Travis is free for open source...

**Comment by matclayton** [comment]
Great point, I have no idea how we didn't spot that! I'll try and open it up.

**Comment by tysonclugg** [comment]
This PR resolves the following issues:
* #143 Is Python3 supported?
* #148 Hardcoded version of 'mock' and 'django-modeldict-yplan' breaks people's projects
* #157 Add backwards compatible python3 support

**Pull request merged**
